@tool
class_name JuiceeSequence
extends Resource

signal started
signal finished
signal stopped
## Emitted just before each effect's apply() is called. Used by graph debugger to highlight blocks.
signal effect_started(effect: JuiceeEffect)
signal effect_finished(effect: JuiceeEffect)

var _cancelled: bool = false
var _playing: bool = false
var _paused: bool = false

## Ordered list of effects to play. Add via the Inspector's "+ Add Effect" button
## or build visually in the JuiceeGraph bottom panel.
@export var effects: Array[JuiceeEffect] = []
## If true, all effects fire at once (parallel). If false, they run one after another (sequential).
@export var parallel: bool = false
## When parallel = true, this is the delay in seconds between each effect's start.
## 0 = all fire simultaneously. Useful for "shotgun" hits where effects cascade.
@export_range(0.0, 2.0, 0.01) var stagger_delay: float = 0.0

@export_group("Graph Editor Metadata")
## Connections between blocks in the graph editor, stored as "from_id:from_port:to_id:to_port".
## Auto-generated by JuiceeGraphEditor — you typically don't edit this manually.
@export var graph_connections: PackedStringArray = []

## Plays the sequence on `context`. Optional `params` dict is forwarded to each effect's
## apply() so effects can react to runtime data (hit direction, damage, etc).
func play(context: Node, params: Dictionary = {}) -> void:
	if effects.is_empty():
		return
	_cancelled = false
	_playing = true
	started.emit()
	if parallel:
		await _play_parallel(context, params)
	else:
		await _play_sequential(context, params)
	_playing = false
	if _cancelled:
		_cancelled = false
		stopped.emit()
	else:
		finished.emit()

## Cancels the sequence and stops every effect inside it. Manual-loop and tween-based
## effects (anything that called `_track()` or checks `_cancelled`) will bail out.
## Safe to call when not playing — does nothing.
func stop() -> void:
	if not _playing:
		# Even if the sequence already ended, an effect with fade_out=false may still
		# be holding state. Stop any effect that reports is_playing().
		for e in effects:
			if e and e.is_playing():
				e.stop()
		return
	_cancelled = true
	for e in effects:
		if e and e.is_playing():
			e.stop()

func is_playing() -> bool:
	return _playing

## Pause at the seam between effects — the currently-running effect finishes,
## then the sequence waits here until resume() is called.
## Has no effect if the sequence is not playing.
func pause() -> void:
	if _playing:
		_paused = true

## Resume a paused sequence. The next effect in the list will start immediately.
func resume() -> void:
	_paused = false

func is_paused() -> bool:
	return _paused

func _play_sequential(context: Node, params: Dictionary) -> void:
	for effect in effects:
		if _cancelled:
			return
		# Hold at the seam between effects while paused.
		while _paused and not _cancelled and is_instance_valid(context) and context.is_inside_tree():
			await context.get_tree().process_frame
		if _cancelled:
			return
		if not effect:
			continue
		effect_started.emit(effect)
		await effect.apply(context, params)
		effect_finished.emit(effect)

func _play_parallel(context: Node, params: Dictionary) -> void:
	var tree := context.get_tree()
	var valid_effects: Array[JuiceeEffect] = []
	for e in effects:
		if e:
			valid_effects.append(e)
	if valid_effects.is_empty():
		return

	# Fire all effects without awaiting — they all run concurrently.
	for i in valid_effects.size():
		if _cancelled:
			return
		effect_started.emit(valid_effects[i])
		valid_effects[i].apply(context, params)
		if stagger_delay > 0.0 and i < valid_effects.size() - 1:
			await tree.create_timer(stagger_delay, true, false, false).timeout

	if _cancelled:
		return

	# Poll every frame until every concurrently-running effect has finished.
	# Also waits for effects that are still in their pre-delay (_pending_start),
	# so a parallel sequence where all effects have delay > 0 doesn't exit
	# before any of them have actually started.
	while not _cancelled and is_instance_valid(context) and context.is_inside_tree():
		var any_active := false
		for eff in valid_effects:
			if eff and (eff.is_playing() or eff._pending_start):
				any_active = true
				break
		if not any_active:
			break
		await tree.process_frame

	for eff in valid_effects:
		effect_finished.emit(eff)
